/*
  # Disable RLS for Testing

  Temporarily disable RLS to allow anonymous access during development
*/

ALTER TABLE business_units DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE partners DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE master_data DISABLE ROW LEVEL SECURITY;